dist: xenial
script:
 - git reset --soft HEAD~1
 - git pull https://gitlab.nic.cz/labs/bird.git master
 - git add --all
 - git commit -m "Travis Commit. Build No.- $TRAVIS_BUILD_NUMBER [skip ci]"
 - pwd
 - git log -3
 - git push -f https://${GH_TOKEN}@github.com/gampu/bird-mirror.git HEAD:master
